rebuild the action yaml with latest changes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -9,6 +9,12 @@ inputs:
   branch:
     description: Branch to publish changes to
     default: gh-pages
+  check:
+    description: Check if the branch is up-to-date
+    default: true
+  reset:
+    description: Reset the branch before publishing
+    default: true
 runs:
   using: composite
   steps:
@@ -18,6 +24,8 @@ runs:
         ACTION_SERVER_URL: ${{github.server_url}}
         ACTION_REPOSITORY: ${{github.repository}}
         ACTION_BRANCH: ${{inputs.branch}}
+        ACTION_CHECK: ${{inputs.check}}
+        ACTION_RESET: ${{inputs.reset}}
         ACTION_SHA: ${{github.sha}}
         ACTION_RUN_ID: ${{github.run_id}}
       working-directory: ${{inputs.working-directory}}
@@ -31,11 +39,16 @@ runs:
         : "${ACTION_SERVER_URL:=""}"
         : "${ACTION_REPOSITORY:=""}"
         : "${ACTION_BRANCH:=""}"
+        : "${ACTION_CHECK:=1}"
+        : "${ACTION_RESET:=1}"
         : "${ACTION_SHA:=""}"
         : "${ACTION_RUN_ID:=0}"
 
         main() {
         	status=0
+
+        	ACTION_CHECK=$(to_bool "$ACTION_CHECK" 1)
+        	ACTION_RESET=$(to_bool "$ACTION_RESET" 1)
 
         	dir=$(mktemp -d)
 
@@ -52,9 +65,27 @@ runs:
         	mv "$dir/.git" .
         	rm -rf "$dir"
 
-        	if git diff-index --quiet HEAD --; then
-        		log "[info] The branch is up-to-date."
-        		return $status
+        	if [ "$ACTION_CHECK" -ne 0 ]; then
+        		log "[info] Checking the branch."
+
+        		if check; then
+        			log "[info] The branch is up-to-date."
+        			return $status
+        		fi
+
+        		log "[info] The branch is not up-to-date."
+        	fi
+
+        	if [ "$ACTION_RESET" -ne 0 ]; then
+        		log "[info] Resetting the branch."
+
+        		reset || status=$?
+        		if [ $status -ne 0 ]; then
+        			log "[error] Failed to reset the branch with status '$status'."
+        			return $status
+        		fi
+
+        		log "[info] Successfully reset the branch."
         	fi
 
         	log "[info] Committing the changes."
@@ -86,11 +117,29 @@ runs:
         		"$1"
         }
 
-        commit() {
+        check() {
+        	if ! git diff --quiet; then
+        		return 1
+        	fi
+
+        	if ! git diff --cached --quiet; then
+        		return 1
+        	fi
+
+        	if [ "$(git ls-files --exclude-standard --others | wc -l)" -ne 0 ]; then
+        		return 1
+        	fi
+
+        	return 0
+        }
+
+        reset() {
         	init=$(git rev-list --max-parents=0 HEAD)
 
         	git reset --hard "$init" --quiet
+        }
 
+        commit() {
         	bare="$ACTION_SERVER_URL/$ACTION_REPOSITORY"
         	head="Update following $(echo "$ACTION_SHA" | cut -c -8)"
         	body="Commit: $bare/commit/$ACTION_SHA/\n"
@@ -100,6 +149,21 @@ runs:
         	git add .
         	git commit --message "$head" --message "$(printf "%b" "$body")" --quiet
         	git push --force --quiet
+        }
+
+        to_bool() {
+        	case "$(printf "%s" "$1" | tr "[:upper:]" "[:lower:]")" in
+        	yes|y|true|t|1)
+        		echo 1
+        		;;
+        	no|n|false|f|0)
+        		echo 0
+        		;;
+        	*)
+        		# shellcheck disable=SC2086
+        		echo $2
+        		;;
+        	esac
         }
 
         log() {
